### ISSUE TITLE
bias correction of ensemble data

### ISSUE THREAD

**Issue by snow73** [ecmwf-projects/ibicus#27]
Hi, 

I am currently exploring if ibicus works for my use case. I would like to bias correct seasonal forecasts and have hindcasts and obs for a certain period. The hindcasts and the actual forecasts are an ensemble (actually of different ensemble size). I would like to use quantile mapping and create the CDF from the whole hindcast ensemble and apply the corrected distribution to all individual ensemble members of the forecast. Is that doable with ibicus? It seems that the numpy arrays only consider time, latitude and longitude. 

Best regards
Dennis

**Comment by jakobwes** [comment]
Hi Dennis,

thanks for opening an issue. Unfortunately currently there is no functionality within ibicus to iterate over ensembles. If there is enough interest we might however consider adding something like this in the future.

Just to make sure I understand correctly: what you want to do is to derive the CDF from the "collapsed" hindcasts, so to merge all hindcasts ensemble members and all dates for which hindcasts exist to derive the "historical" CDF for quantile mapping? If yes then it also shouldn't be too difficult to write something like this yourself, using ibicus. For example if your hindcasts `cm_hist` and the forecasts `cm_future` are of the form `[time, lat, lon, ensemble_nr]` then you could collapse the hindcasts into the form `[time * ensemble, lat, lon]` using 

`cm_hist_collapsed = np.reshape(cm_hist, (-1, nr_of_lats, nr_of_lons))`

Then using a debiaser you could just iterate over all ensemble members, eg.:

```
debiaser = QuantileMapping()

debiased_cm_fut = np.empty_like(cm_fut)

for i in range(cm_fut.shape[-1]):
    debiased_cm_fut[:, :, :, i] = debiaser.apply(obs, cm_hist_collapsed, cm_future[:, :, :, i])
```

You might need to take some extra care of things like running windows, but you can just deactivate them using `running_window_mode = False` in the debiaser-initialization (and at least for bias correction of seasonal forecasts I think running windows are nonstandard).

I hope that helps. Let us know if you have any other questions.

Best,
Jakob

**Comment by snow73** [comment]
Hi Jakob,

thanks for the quick response. I closed the issue in the mean-time as I came to the same solution which you pointed out but it's very helpful to see how you would implement it. I need to sort out some other things as I only work with land points (and therefore have NaN values in my array) but hope the failsafe flag should help with that. 

Best regards
Dennis

**Comment by jakobwes** [comment]
Hi Dennis,

glad that it helped! Generally the failsafe flag should be able to take care of land masks and NaN values. Let us know should you encounter any issues or if you have any other questions.

Best,
Jakob
