### ISSUE TITLE
Reflections of the problem

### ISSUE THREAD

**Issue by theshyyi** [ecmwf-projects/ibicus#28]
Ran into this problem while using ibicus
![Snipaste_2024-09-27_10-33-36](https://github.com/user-attachments/assets/964520c0-3b90-4553-8580-a76aca651989)

After I unified the spatial dimensions of obs,hist and fut (x = 88, y = 88) including the latitude and longitude ranges of all three are the same (34.15~42.85N, 111.15~119.85E), but still this error occurs.  It is very urgent to get your reply!

**Comment by jakobwes** [comment]
Hi, unfortunately we don't have enough information to know what the issue is. What are the exact shapes of the `obs`, `cm_hist` and `cm_future` objects (the output of `obs.shape`)?

**Comment by theshyyi** [comment]
Thank you for your reply, in this afternoon when I double-checked the running code, found that some steps in the code for my data is redundant, the lines of code after commenting can run normally, thank you very much for your answer.
![Snipaste_2024-09-27_19-12-58](https://github.com/user-attachments/assets/3a42418c-be30-49f1-9d41-c76959d10187)
The screenshot shows my commented code.

**Comment by jakobwes** [comment]
No worries. Let us know should you encounter other issues.
