### ISSUE TITLE
Feedback on issues

### ISSUE THREAD

**Issue by theshyyi** [ecmwf-projects/ibicus#29]
Hello, I get a warning when using the ibicus library for deviation correction of temperature and then an error is reported!

The following is the reason for the error report:
UserWarning: obs contains values outside the reasonable physical range of [100, 400] for the variable: Daily mean near-surface air temperature. This might be due to different units of to data problems. It is recommended to check the input.

Since I currently use temperature units in Celsius, the approximate temperature range is -36° to 42°. So I'm wondering which temperature unit is used in ibicus that would allow values to fall between 100 and 400?
![Uploading Snipaste_2024-10-23_19-32-41.jpg…]()

**Comment by jakobwes** [comment]
Hi, thank you for raising an issue. Unfortunately, we don't currently have enough information to see where the problem could lie. Would you mind sharing the error message?

Generally the methods implemented assume temperature in Kelvin, so you could convert your temperature ranges to that to get rid of the warning.
