### ISSUE TITLE
Quantiles out of range & how to handle NaN values 

### ISSUE THREAD

**Issue by JacquelineKies** [ecmwf-projects/ibicus#30]
I am encountering the error message: ‘ValueError: Quantiles must be in the range [0, 1].

I suspect this issue is related to NaN values in my dataset. I am working with ERA5-Land and NEX-GDDP-CMIP6 data, which does not include data from the oceans. When I fill the NaN values with zeros, the function works. However, I am concerned that filling NaNs with zeros might skew my statistics and quantiles.

Could someone please confirm if this error is indeed related to NaN values? If so, what is the best way to handle NaNs without affecting the statistical integrity of my data? FYI, the shapes of the data do align. 

Thank you for your help!

Best regards, 

Jacqueline

**Comment by jakobwes** [comment]
Dear Jacqueline,

sorry for the late response.

The debiaser.apply function has a ``failsafe`` option. This ensures, that should the debiaser encounters an error during application (e.g. when it encounters nan values), it continues at other locations and gives out np.nan values at the location where the error was encountered. So you could write:

```debiased_cm_future = debiaser.apply(obs, cm_hist, cm_future, ..., failsafe = True)```

This will give out a debiased dataset, with np.nan at any location where the debiaser encountered an error. This means that the locations with nan values before bias adjustment will also be filled with nan-values after bias adjustment.

I hope that helps.

Best,
Jakob
